version: "3.3"
services:
  db:
    image: mysql:5.7
    hostname: mysql
    volumes:
      - /var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - db-test
networks:
  db-test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "111.111.10.0/24"
#        - subnet: "192.168.220.0/24"